final_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vaccination_records.urls")),
]

vaccination_records/urls.py
from django.urls import path

from . import views

app_name = "vaccination_records"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("get_records", views.get_records, name="get_records"),
    path("get_record/<int:record_id>", views.get_record, name="get_record"),
    path("add_record", views.add_record, name="add_record"),
]

vaccination_records/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


# vaccine information
class Vaccine_information(models.Model):
    dosage_sequence = models.CharField(max_length=32)
    date_administered = models.DateField()
    vaccine_brand = models.CharField(max_length=255)
    vaccinator = models.CharField(max_length=255)

    def serialize(self):
        return {
            "dosage_sequence": self.dosage_sequence,
            "date_administered": self.date_administered,
            "vaccine_brand": self.vaccine_brand,
            "vaccinator": self.vaccinator,
        }

    def __str__(self):
        return f"{self.dosage_sequence} {self.vaccine_brand} {self.date_administered}"


class Personal_information(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="added_records")
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)
    birthdate = models.DateField(help_text="Date of birth")
    date_created = models.DateTimeField(auto_now_add=True)
    vaccine_infos = models.ManyToManyField(Vaccine_information, related_name="personal_info")

    def serialize(self):
        return {
            "id": self.id,
            "name": f"{self.first_name} {self.last_name}",
            "address": self.address,
            "contact_number": self.contact_number,
            "gender": self.gender,
            "birthday": self.birthdate,
            "date_created": self.date_created.strftime("%b %d %Y, %I:%M %p"),
            "vaccine_infos": [record.serialize() for record in self.vaccine_infos.all()],
        }

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

vaccination_records/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import User, Vaccine_information, Personal_information


def index(request):
    # Authenticated users
    if request.user.is_authenticated:
        return render(request, "vaccination_records/index.html")

    # Everyone else is prompted to sign in
    else:
        return HttpResponseRedirect(reverse("vaccination_records:login"))


@csrf_exempt
@login_required
def get_record(request, record_id):
    record = {}

    try:
        record = Personal_information.objects.get(user=request.user, pk=record_id)
    except Personal_information.DoesNotExist:
        return JsonResponse({"error": "record not found."}, status=404)

    # return serialized record
    if request.method == "GET":
        return JsonResponse(record.serialize())
    else:
        return JsonResponse({"error": "GET request required."}, status=400)


@csrf_exempt
@login_required
def get_records(request):
    records = Personal_information.objects.filter(user=request.user).order_by(
        "-date_created"
    )

    return JsonResponse([record.serialize() for record in records], safe=False)


@csrf_exempt
@login_required
def add_record(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    try:
        data = json.loads(request.body)
        first_name = data.get("first_name", "")
        last_name = data.get("last_name", "")
        address = data.get("address", "")
        contact_number = data.get("contact_number", "")
        gender = data.get("gender", "")
        birthdate = data.get("birthdate", "")

        personal_info = Personal_information.objects.create(
            user=request.user,
            first_name=first_name,
            last_name=last_name,
            address=address,
            contact_number=contact_number,
            gender=gender,
            birthdate=birthdate,
        )
        personal_info.save()
        new_added = Personal_information.objects.get(pk=personal_info.id)
        jsonified_vaccine_infos = data.get("vaccine_infos", "")
        vaccine_infos = json.loads(jsonified_vaccine_infos)

        for info in vaccine_infos:
            # if ((info["dosage_sequence"] != "") and (info["date_administered"] != "") and (info["vaccine_brand"] != "") and (info["vaccinator"]) != ""):
            if ((info["dosage_sequence"]) and (info["date_administered"]) and (info["vaccine_brand"]) and (info["vaccinator"])):
                new_vaccine_info = Vaccine_information.objects.create(
                    dosage_sequence=info["dosage_sequence"],
                    date_administered=info["date_administered"],
                    vaccine_brand=info["vaccine_brand"],
                    vaccinator=info["vaccinator"],
                )
                new_vaccine_info.save()
                new_added.vaccine_infos.add(new_vaccine_info)

        return JsonResponse({"message": "success"}, status=201)

    except Personal_information.DoesNotExist:
        return JsonResponse({"error": "record not found"}, status=404)


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=email, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("vaccination_records:index"))
        else:
            return render(
                request,
                "vaccination_records/login.html",
                {"message": "Invalid email and/or password."},
            )
    else:
        return render(request, "vaccination_records/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("vaccination_records:index"))


def register(request):
    if request.method == "POST":
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request,
                "vaccination_records/register.html",
                {"message": "Passwords must match."},
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(email, email, password)
            user.save()
        except IntegrityError as e:
            print(e)
            return render(
                request,
                "vaccination_records/register.html",
                {"message": "Email address already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("vaccination_records:index"))
    else:
        return render(request, "vaccination_records/register.html")

vaccination_records/templates/vaccination_records/index.html
{% extends "vaccination_records/layout.html" %}
{% load static %}

{% block body %}
<h5>{{ request.user.username }}</h5>

<button class="btn btn-sm btn-outline-primary" id="records">Vaccination records</button>
<button class="btn btn-sm btn-outline-primary" id="create">Create new record</button>
<button class="btn btn-sm btn-outline-primary" id="about">About</button>
<a class="btn btn-sm btn-outline-primary" href="{% url 'vaccination_records:logout' %}">Log Out</a>
<hr>
<div id="record-view">
</div>
<div id="records-view">
</div>
<div id="about-view">
</div>

<div id="create-view">
  <div class="row">
    <div class="col-md-12 order-md-1">
      <h3 class="mb-3">Personal Information</h3>
      <form id="recordsForm">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-9 mb-3">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" placeholder="" required="">
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zipCode">Zip Code</label>
            <input type="text" class="form-control" id="zipCode" placeholder="" required="">
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>
        <div class="row">

          <div class="col-md-4 mb-3">
            <label for="date">Date</label>
            <div class="input-group date" id="datepicker">
              <input type="text" id="birthdate" class="form-control">
              <span class="input-group-append">
                <span class="input-group-text bg-white">
                  <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>

          <div class="col-md-4 mb-3">
            <label for="contactNumber">Contact Number</label>
            <input type="text" class="form-control" id="contactNumber" placeholder="" required="">
            <div class="invalid-feedback">
              contact number required.
            </div>
          </div>

          <div class="col-md-4 mb-3">
            <label for="gdr">Gender</label>

            <div id="gdr" class="form-control d-flex flex-row border-0">
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="gender" id="inlineRadio1" value="female"
                  checked="checked">
                <label class="form-check-label" for="inlineRadio1">Female</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="gender" id="inlineRadio2" value="male">
                <label class="form-check-label" for="inlineRadio2">Male</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="gender" id="other" value="other">
                <label class="form-check-label" for="inlineRadio2">Other</label>
              </div>
            </div>
          </div>

        </div>
        <hr>
        <div class="row">
          <h3 class="mb-3">Vaccine Information</h3>
        </div>
        <div class="row">
          <div class="col-md-3 mb-1 px-1">
            <label for="dosageSequence1">Dosage Sequence</label>
            <input type="text" class="form-control" id="dosageSequence1" value="First Dose" required="">
            <div class="invalid-feedback">
              Dosage sequence required.
            </div>
          </div>
          <div class="col-md-3 mb-1 px-1">
            <label for="vaccineBrand1">Vaccine Brand</label>
            <input type="text" class="form-control" id="vaccineBrand1" placeholder="" required="">
            <div class="invalid-feedback">
              Vaccine brand required.
            </div>
          </div>
          <div class="col-md-4 mb-1 px-1">
            <label for="vaccinator1">Name of vaccinator</label>
            <input type="text" class="form-control" id="vaccinator1" placeholder="" required="">
            <div class="invalid-feedback">
              Name of vaccinator required.
            </div>
          </div>

          <div class="col-md-2 mb-1 px-1">
            <label for="date">Date</label>
            <div class="input-group date" id="datepicker1">
              <input type="text" id="dateAdministered1" class="form-control" required="">
              <span class="input-group-append">
                <span class="input-group-text bg-white">
                  <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
            <div class="invalid-feedback">
              Date administered required.
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="dosageSequence2" value="Second Dose">
          </div>
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="vaccineBrand2" placeholder="">
          </div>
          <div class="col-md-4 mb-1 px-1">
            <input type="text" class="form-control" id="vaccinator2" placeholder="">
          </div>

          <div class="col-md-2 mb-1 px-1">
            <div class="input-group date" id="datepicker2">
              <input type="text" id="dateAdministered2" class="form-control">
              <span class="input-group-append">
                <span class="input-group-text bg-white">
                  <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="dosageSequence3" value="First Booster">
          </div>
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="vaccineBrand3" placeholder="">
          </div>
          <div class="col-md-4 mb-1 px-1">
            <input type="text" class="form-control" id="vaccinator3" placeholder="">
          </div>

          <div class="col-md-2 mb-1 px-1">
            <div class="input-group date" id="datepicker3">
              <input type="text" id="dateAdministered3" class="form-control">
              <span class="input-group-append">
                <span class="input-group-text bg-white">
                  <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="dosageSequence4" value="Second Booster">
          </div>
          <div class="col-md-3 mb-1 px-1">
            <input type="text" class="form-control" id="vaccineBrand4" placeholder="">
          </div>
          <div class="col-md-4 mb-1 px-1">
            <input type="text" class="form-control" id="vaccinator4" placeholder="">
          </div>
          <div class="col-md-2 mb-1 px-1">
            <div class="input-group date" id="datepicker4">
              <input type="text" id="dateAdministered4" class="form-control">
              <span class="input-group-append">
                <span class="input-group-text bg-white">
                  <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>
        </div>
        <hr>
        <input type="submit" class="btn btn-primary" />
      </form>
    </div>
  </div>

</div>

{% endblock %}

{% block script %}
<script src="{% static 'vaccination_records/index.js' %}"></script>
<script type="text/javascript">
  $(function () {
    $('#datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
  $(function () {
    $('#datepicker1').datepicker({format: 'yyyy-mm-dd'});
  });
  $(function () {
    $('#datepicker2').datepicker({format: 'yyyy-mm-dd'});
  });
  $(function () {
    $('#datepicker3').datepicker({format: 'yyyy-mm-dd'});
  });
  $(function () {
    $('#datepicker4').datepicker({format: 'yyyy-mm-dd'});
  });
</script>
{% endblock %}

vaccination_records/templates/vaccination_records/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}Vaccination Records{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'vaccination_records/styles.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
  {% block script %}
  {% endblock %}
</head>

<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <!-- Footer -->
  <div class="d-flex justify-content-end bg-dark text-white fixed-bottom">
    <p class="d-flex justify-content-end m-0 mr-2">© 2022 rodvicj</p>
  </div>

</body>

</html>

vaccination_records/templates/vaccination_records/login.html
{% extends "vaccination_records/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'vaccination_records:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'vaccination_records:register' %}">Register here.</a>

{% endblock %}

vaccination_records/templates/vaccination_records/register.html
{% extends "vaccination_records/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'vaccination_records:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'vaccination_records:login' %}">Log In here.</a>

{% endblock %}